export const CONSTANTS = {
    ARMOUR_REDUCTION_PERCENT: 0.75,
    BOSS_ROUND: 10,
    BURN_DMG: 10,
    DELAY: 3500,
    ATTACK_TIMEOUT: 500,
    MAX_SET_ROUND: 20,
    HEADCOUNT: 3,
    BASE_BOSS_HP: 15,
    BASE_BOSS_DMG: 10,
}